---
title: "Métodos"
subtitle: "Métodos aplicados a los métodos"
format: html
---

::: {.callout-note appearance="minimal" icon=true}
**Métodos de construcción del conocimiento** 

Se establecen 3 rutas básicas o modelos de construcción del conocimiento, de manera de distinguir el rol de los dispositivos de interacción en el proceso de aprendizaje, investigación y síntesis.

Todos los modelos resultantes se diseñan con principios FAIR/CARE, con consideración de términos y condiciones para la protección de datos personales.

  1. **Modelo humano**. Modelo de red de relaciones humanas, grupos, _pedigrees_).  Personas humanas interactuamos y convenimos colaborar en un proyecto. Se establecen relaciones vinculadas a las historias de vida de las personas para el desarrollo del proyecto. La toma de decisiones es realizada por personas humanas.

  2. **Modelo híbrido**. Personas humanas usamos dispositivos con asistencia de Inteligencia Artificial para desarrollar el proyecto a todos los niveles hasta donde llega la mediación humana. La toma de decisiones es co-participada con asistentes de IA.

  3. **Modelo autónomo**. Sistemas automatizados de desarrollo del proyecto mediado por agentes de IA.

:::

