---
title: "Plan de Gestión de Datos"
subtitle: "Componentes del ecosistema de gestión del proceso de aprendizaje, investigación y síntesis"
format: html
---

::: {.callout-note appearance="minimal" icon=true}
**Ecosistema de interacción de personas humanas, dispositivos y aplicaciones de aprendizaje, investigación y síntesis** 

**Gestión operativa del proyecto**

Aplicaciones y sistemas como [STAPLE](https://app.staplescience.com/), que combinan la estandarización FAIR/CARE con estándares de investigación académica. 

STAPLE articula con OSF y el resto de los componentes del ecosistema de investigación, [ver documentación STAPLE](https://staplescience.com/documentation/)

- Proyecto

Variación Fenotípica de la Vida Silvestre en el Ámbito Doméstico e Infraestructura Digital Abierta

- Descripción

Ecosistema transdisciplinar y dispositivo interactivo enfocado en las rutas y facetas de la variación fenotípica en el ámbito doméstico, la gestión de datos bajo principios FAIR/CARE, y la automatización de la difusión del conocimiento.

**Gestión académica del proyecto**

Pre-registro y registro de componentes de proyecto, metadatos y plataforma de gestión del proyecto vía [Open Science Framework](https://osf.io)

- Proyecto

Phenotypic variation of wildlife in the domestic environment: a systematic review

- Licencia "CC-BY-4.0"

- Cómo usar principios FAIR y CARE en este proyecto.

:::


