---
title: "Información Extra"
format: html
---

**Plataformas, apps y dispositivos de mediación con la vida silvestre**

Enlaces a desarrollos relativos a la vida silvestre en el ámbito doméstico.

::: {.callout-note appearance="simple" title="🔎 Aplicaciones y sistemas"}

Aplicaciones y sistemas para el aprendizaje, la investigación y síntesis sobre el conocimiento de las interacciones bióticas en el ámbito doméstico

(!) _En orden alfabético por su nombre de origen._

### Escala Global
- [**Botanical Information and Ecology Network**](https://bien.nceas.ucsb.edu/bien/) - una herramienta de información sobre el conocimiento disponible sobre la vida de las plantas.

 - [**Ecological Metadata Language**](https://eml.ecoinformatics.org/) - sistema de "clase herméutica", donde se define el lenguaje de metadatos sobre conceptos y variables usados en ecología.

- [**Encyclopedia of Life**](https://eol.org/) — acceso global al conocimiento sobre la vida en la Tierra.

- [**Global Biodiversity Information Facility**](https://www.gbif.org) — fuente básica global de información sobre biodiversidad.

- [**iNaturalist**](https://www.inaturalist.org/) - app para la búsqueda de información, identificación y generación de registros sobre la distribución geográfica, características fenotípicas y de historia de vida, de especies de la vida silvestre o domesticadas.

- [**MapBiomas**](https://argentina.mapbiomas.org/) - plataforma de red global multi-institucional, que monitorea cambios e impactos en sistemas de uso del suelo ( _land systems_ ). 

- [**Map of Life**](https://mol.org/) - herramienta de información sobre indicadores ecológicos basados en la distribución geográfica y dinámica temporal de la ocurrencia de especies.

- [**OCCUR**](https://ecoinformatic.shinyapps.io/OCCUR/) - herramienta que facilita el proceso de filtrado, limpieza y validación de los registros de ocurrencia de especies en repositorios de datos.

- [**Ocean Biodiversity Information System**](https://obis.org/) - sistema de información sobre biodiversidad marina.

- [**re3data**](https://www.re3data.org/) - registro de repositorios de datos de investigación; el buscador está al ingresar; usa palabras clave para encontrar portales, por ejemplo: "biodiversidad".

- [**SDMtoolbox**](http://www.sdmtoolbox.org/) - caja de herramientas donde se desarrollan y despliegan aplicaciones para la modelación de la distribución de especies y la estimación de variables de análisis.

- [**Tipología Global de Ecosistemas**](https://global-ecosystems.org/es/explore) - plataforma de categorización de biomas en grandes divisiones y transiciones.

- [**Wallace EcoMod**](https://wallaceecomod.github.io/) - plataforma para el modelado de nicho ecológico y distribución de especies.

:::
